config/routes.rb
Rails.application.routes.draw do
  constraints subdomain: /.+/ do 
    devise_for :users, controllers: {
      registrations: 'users/registrations',
      passwords: 'users/passwords',
      sessions: 'users/sessions',
      confirmations: 'users/confirmations'
    }
    resources :members
    resources :categories
    devise_scope :user do
      get '/users/sign_out' => 'devise/sessions#destroy'
      get 'login_across_session', to: 'users/sessions#login_across_session'
    end
    get 'dashboard', to: "companies#dashboard"
    resources :installment_plans
    root to: "companies#dashboard",as: 'root_dashboard', :via => :get
  end
  constraints(subdomain: '') do
    root to: "home#index", via: :get
    devise_for :users, only: :registrations, controllers: {
      registrations: 'users/registrations'
    }
    resources :user_companies, only: :index do
      get 'find', on: :collection
    end
  end

  match "*path", to: "catch_all#index", via: :all
end

app/models/company.rb
class Company < ApplicationRecord
  validates :name,      length:    { minimum: 3, maximum: 35 }, uniqueness: { case_sensitive: false }
  validates :subdomain, format:    { with: /\A([a-zA-Z0-9]*[a-zA-Z]+[a-zA-Z0-9]*)\z/ }
  validates :subdomain, length:    { minimum: 3, maximum: 35 }, uniqueness: { message: "has already been taken, change the company name", case_sensitive: false }
  before_validation :setup_subdomain, :if=> :new_record?

  has_many :users
  has_many :categories
  has_many :installment_plans

  not_multitenant!

  def self.current_tenant_id=(tenant_id)
    Thread.current[:tenant_id] = tenant_id
    if tenant_id.present?
      Thread.current[:tenant] = find_by(id: tenant_id)
    else
      Thread.current[:tenant] = nil
    end
  end

  def self.current_tenant_id
    Thread.current[:tenant_id]
  end

  def self.current_tenant=(company)
    if company.present?
      Thread.current[:tenant] = company
      Thread.current[:tenant_id] = company.id
    else
      Thread.current[:tenant] = nil
      Thread.current[:tenant_id] = nil
    end
  end

  def self.current_tenant
    Thread.current[:tenant]
  end

  private

  def setup_subdomain
    self.subdomain = self.name.gsub(/[^0-9A-Za-z]/, '')
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  load_and_authorize_resource

  def dashboard
    @members = Company.current_tenant.users
    @categories = Company.current_tenant.categories
    @products = Company.current_tenant.products
  	respond_to do |format|
      format.html
    end
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/dashboard.html.erb
<h1 class="d-flex justify-content-center p-4">Welcome To Smart Installments</h1>
<div class="container">
  <h2 class="d-flex justify-content-center">Dashboard</h2>
  <h4>Members List</h4>
  <table class="table table-borderless">
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @members.each do |member| %>
        <tr>
          <td><%= member.full_name %></td>
          <td><%= member.email %></td>
          <td class="d-flex">
            <%= link_to 'New', new_member_path, class: 'btn btn-secondary me-2' %>
            <%= link_to 'View', member_path(member), class: 'btn btn-secondary me-2' %>
            <%= link_to 'Edit', edit_member_path(member), class: 'btn btn-secondary me-2' %>
            <%= button_to 'Delete', member_path(member), class: 'btn btn-secondary', method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <h4 class="py-4">Manage Categories</h4>
  <%= link_to 'New', new_category_path, class: 'btn btn-secondary me-2' %>
  <% if @categories.present? %>
    <table class="table table-borderless">
      <thead>
        <tr>
          <th>Name</th>
        </tr>
      </thead>
      <tbody>
        <% @categories.each do |category| %>
          <tr>
            <td><%= category.name %></td>
            <td class="d-flex">
              <%= link_to 'View', category_path(category), class: 'btn btn-secondary me-2' %>
              <%= link_to 'Edit', edit_category_path(category), class: 'btn btn-secondary me-2' %>
              <%= link_to 'Delete', category_path(category), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-secondary me-2' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
  <h4>Create Products</h4>
  <%= link_to 'New', new_product_path, class: 'btn btn-secondary me-2' %>
  <table class="table table-borderless">
    <thead>
      <tr>
        <th>Name</th>
        <th>Identification Number</th>
        <th>Description</th>
      </tr>
    </thead>
    <tbody>
      <% @products.each do |product| %>
        <tr>
          <td><%= product.name %></td>
          <td><%= product.identification_number %></td>
          <td><%= product.description %></td>
          <td class="d-flex">
            <%= link_to 'View', product_path(product), class: 'btn btn-secondary me-2' %>
            <%= link_to 'Edit', edit_product_path(product), class: 'btn btn-secondary me-2' %>
            <%= link_to 'Delete', product_path(product), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-secondary me-2' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to "Log out", destroy_user_session_path, method: :delete, class: 'btn btn-primary' %>
</div>