config/routes.rb
Rails.application.routes.draw do
  constraints subdomain: /.+/ do 
    devise_for :users, controllers: {
      registrations: 'users/registrations',
      passwords: 'users/passwords',
      sessions: 'users/sessions',
      confirmations: 'users/confirmations'
    }
    resources :members
    resources :categories
    devise_scope :user do
      get '/users/sign_out' => 'devise/sessions#destroy'
      get 'login_across_session', to: 'users/sessions#login_across_session'
    end
    get 'dashboard', to: "companies#dashboard"
    resources :installment_plans
    root to: "companies#dashboard",as: 'root_dashboard', :via => :get
  end
  constraints(subdomain: '') do
    root to: "home#index", via: :get
    devise_for :users, only: :registrations, controllers: {
      registrations: 'users/registrations'
    }
    resources :user_companies, only: :index do
      get 'find', on: :collection
    end
  end

  match "*path", to: "catch_all#index", via: :all
end

app/models/installment_plan.rb
class InstallmentPlan < ApplicationRecord
  include CanCanRules

  belongs_to :company
  belongs_to :category
  sequenceid :company, :installment_plans
  before_destroy :check_for_inclusion_in_plots
  validate :must_have_payment_amount

  validates :no_of_biannual_or_quarterly_payments, :no_of_monthly_payments, presence: true,
                     numericality: { greater_than: 0, less_than_or_equal_to: 100_000_000 }

  validates :biannual_payment, :quarterly_payment, :allocation_amount,
            numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 100_000_000 },
            allow_blank: true

  validates :monthly_payment, :booking_amount, presence: true,
                                numericality: { greater_than: 0, less_than_or_equal_to: 10_000_000 }

  attr_accessor :payment_frequency

  def not_associated_with_any_plot?
    # TODO donot destroy installment plan if it is linked with any plot installment
    true
  end

  def total_price
    price = booking_amount
    price += allocation_amount if allocation_amount.present?
    price += (monthly_payment * no_of_monthly_payments)
    price += (biannual_payment * no_of_biannual_or_quarterly_payments) if biannual_payment.present?
    price += (quarterly_payment * no_of_biannual_or_quarterly_payments) if quarterly_payment.present?
    price
  end

  private

  def must_have_payment_amount
    unless biannual_payment.present? || quarterly_payment.present?
      errors.add(:base, "Please enter either biannual or quarterly payment amount")
    end
  end

  def check_for_inclusion_in_plots
    # TODO donot destroy installment plan if it is linked with any plot installment
    true
  end
end

app/controllers/installment_plans_controller.rb
class InstallmentPlansController < ApplicationController
  authorize_resource :company, instance_name: :current_company
  load_and_authorize_resource find_by: :sequence_num, through: :current_company

  # GET /installment_plans
  def index
    respond_to do |format|
      format.html
    end
  end

  # GET /installment_plans/1
  def show
    respond_to do |format|
      format.html
    end
  end

  # GET /installment_plans/new
  def new
    respond_to do |format|
      format.html
    end
  end

  # GET /installment_plans/1/edit
  def edit
    respond_to do |format|
      format.html
    end
  end

  # POST /installment_plans
  def create
    begin
      @installment_plan.company = Company.current_tenant
      @installment_plan.save!
    rescue StandardError => e
      flash[:alert] = e.message
    end
    
    respond_to do |format|
      if @installment_plan.persisted?
        format.html { redirect_to installment_plan_path(@installment_plan), notice: "Installment plan was successfully created." }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH /installment_plans/1
  def update
    respond_to do |format|
      if @installment_plan.update(installment_plan_params)
        format.html { redirect_to installment_plan_url(@installment_plan), notice: "Installment plan was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /installment_plans/1
  def destroy
    @installment_plan.destroy

    respond_to do |format|
      format.html { redirect_to installment_plans_url, notice: "Installment plan was successfully destroyed." }
    end
  end

  private

  def installment_plan_params
    params.require(:installment_plan).permit(
      :category_id,
      :booking_amount,
      :allocation_amount,
      :biannual_payment,
      :monthly_payment,
      :quarterly_payment,
      :no_of_monthly_payments,
      :no_of_biannual_or_quarterly_payments
    )
  end
end

app/helpers/installment_plans_helper.rb
module InstallmentPlansHelper
  extend ActionView::Helpers

  def categories_options(categories, selected_value = nil)
    options_for_select(categories.map { |category| [category.name, category.id] }, selected_value)
  end
end

app/views/installment_plans/_form.html.erb
<%= form_with(model: installment_plan) do |form| %>
  <% if installment_plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(installment_plan.errors.count, "error") %> prohibited this installment_plan from being saved:</h2>

      <ul>
        <% installment_plan.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.label 'Category' %>
  <%= form.select :category_id, categories_options(Company.current_tenant.categories, installment_plan.category&.id), class: 'form-control' %>
  <br/>

  <%= form.label :booking_amount, "Booking Amount" %>
  <%= form.number_field :booking_amount, min: 0, step: 'any', class: 'form-control w-50 mb-3' %>
 
  <%= form.label :allocation_amount, "Allocation Amount" %>
  <%= form.number_field :allocation_amount, min: 0, step: 'any', class: 'form-control w-50 mb-3' %>

  <%= form.label :payment_frequency %>
  <%= form.select :payment_frequency, [['Biannual', 'biannual'], ['Quarterly', 'quarterly']] %>

  <div id="biannual_fields" style="display: block;">
    <%= form.label :biannual_payment, "Biannual Payment" %>
  <%= form.number_field :biannual_payment, min: 0, step: 'any', class: 'form-control w-50 mb-3' %>
  </div>

  <div id="quarterly_fields" style="display: none;">
    <%= form.label :quarterly_payment, "Quaterly Payment" %>
    <%= form.number_field :quarterly_payment, min: 0, step: 'any', class: 'form-control w-50 mb-3' %>
  </div>

  <%= form.label :monthly_payment, "Monthly Payment" %>
  <%= form.number_field :monthly_payment, min: 0, step: 'any', class: 'form-control w-50 mb-3' %>

  <%= form.label :no_of_monthly_payments, "No of monthly payments" %>
  <%= form.number_field :no_of_monthly_payments, min: 0, step: 'any', class: 'form-control w-50 mb-3' %>

  <%= form.label :no_of_biannual_or_quarterly_payments, "No of Quaterly/Biannual payments" %>
  <%= form.number_field :no_of_biannual_or_quarterly_payments, min: 0, step: 'any', class: 'form-control w-50' %>

  <%= form.submit 'Create installment plan', class: 'btn btn-primary mt-3' %>
<% end %>

<script>
  $(document).ready(function() {
    $('#installment_plan_payment_frequency').change(function() {
      if ($(this).val() === 'biannual') {
        $('#biannual_fields').show();
        $('#quarterly_fields').hide();
      } else if ($(this).val() === 'quarterly') {
        $('#biannual_fields').hide();
        $('#quarterly_fields').show();
      }
    });
  });
</script>

app/views/installment_plans/edit.html.erb
<h1>Editing Installment Plan</h1>

<%= render 'form', installment_plan: @installment_plan %>

<%= link_to 'Show', @installment_plan %> |
<%= link_to 'Back', installment_plans_path %>

app/views/installment_plans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Installment Plans</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @installment_plans.each do |installment_plan| %>
      <tr>
        <td><%= link_to_if(can?(:show, installment_plan), installment_plan.sequence_num, installment_plan, class: 'btn btn-secondary me-2') %></td>
        <% if can?(:update, installment_plan) %>
          <td><%= link_to 'Edit', edit_installment_plan_path(installment_plan), class: 'btn btn-secondary me-2' %></td>
        <% end %>
        <% if can?(:destroy, installment_plan) %>
          <td><%= link_to 'Destroy', installment_plan, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-secondary me-2' %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Installment Plan', new_installment_plan_path, class: 'btn btn-primary' %>

app/views/installment_plans/new.html.erb
<h1>New Installment Plan</h1>

<%= render 'form', installment_plan: @installment_plan %>

app/views/installment_plans/show.html.erb
<h5>Installment Plan:<%= @installment_plan.sequence_num %></h5>

<p>Category: <%= @installment_plan.category.name %></p>
<p>Total Price: <%= @installment_plan.total_price %></p>
<p>Booking Amount: <%= @installment_plan.booking_amount %></p>

<% if @installment_plan.allocation_amount.present? %>
  <p>Allocation Amount: <%= @installment_plan.allocation_amount %></p>
<% end %>

<% if @installment_plan.biannual_payment.present? %>
  <p>Biannual Payment(<%= @installment_plan.no_of_biannual_or_quarterly_payments %>): <%= @installment_plan.biannual_payment %></p>
<% end %>

<% if @installment_plan.quarterly_payment.present? %>
  <p>Quarterly Payment(<%= @installment_plan.no_of_biannual_or_quarterly_payments %>): <%= @installment_plan.quarterly_payment %></p>
<% end %>

<p>Monthly Payment(<%= @installment_plan.no_of_monthly_payments %>): <%= @installment_plan.monthly_payment %></p>

<%= link_to 'Edit', edit_installment_plan_path(@installment_plan) %>