config/routes.rb
Rails.application.routes.draw do
  constraints subdomain: /.+/ do 
    devise_for :users, controllers: {
      registrations: 'users/registrations',
      passwords: 'users/passwords',
      sessions: 'users/sessions',
      confirmations: 'users/confirmations'
    }
    resources :members
    resources :categories
    devise_scope :user do
      get '/users/sign_out' => 'devise/sessions#destroy'
      get 'login_across_session', to: 'users/sessions#login_across_session'
    end
    get 'dashboard', to: "companies#dashboard"
    resources :installment_plans
    root to: "companies#dashboard",as: 'root_dashboard', :via => :get
  end
  constraints(subdomain: '') do
    root to: "home#index", via: :get
    devise_for :users, only: :registrations, controllers: {
      registrations: 'users/registrations'
    }
    resources :user_companies, only: :index do
      get 'find', on: :collection
    end
  end

  match "*path", to: "catch_all#index", via: :all
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :company
  has_many :installment_plans
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  authorize_resource :company, instance_name: :current_company
  load_and_authorize_resource

  # GET /categories
  def index
    respond_to do |format|
      format.html
    end
  end

  # GET /categories/1
  def show
    respond_to do |format|
      format.html
    end
  end

  # GET /categories/new
  def new
    respond_to do |format|
      format.html
    end
  end

  # GET /categories/1/edit
  def edit
    respond_to do |format|
      format.html
    end
  end

  # POST /categories
  def create
    begin
      @category.company = Company.current_tenant
      success = @category.save! 
    rescue StandardError => e
      flash[:alert] = e.message
      success = false
    end

    respond_to do |format|
      if success
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH /categories/1
  def update
    begin
      success = @category.update!(category_params)
    rescue StandardError => e
      flash[:alert] = e.message
      success = false
    end

    respond_to do |format|
      if success
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /categories/1
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

end

app/views/categories/_form.html.erb
<div class="container">
  <%= form_for local_assigns[:category], url: local_assigns[:form_url], html: { method: local_assigns[:form_method] } do |f| %>
    <div class="pb-3">      
      <%= f.label 'Category Name' %>
      <%= f.text_field :name, class: 'form-control', placeholder: 'Enter Category Name' %>
    </div>     
    <%= f.submit local_assigns[:submit_button_label], class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/categories/edit.html.erb
<h1 class="d-flex justify-content-center p-4">Edit Category</h1>
<%= render partial: 'form', locals: { category: @category, form_url: category_path(@category), form_method: :patch, submit_button_label: "Update Category" } %>

app/views/categories/index.html.erb
<h1 class="d-flex justify-content-center p-4">All Categories</h1>
<div class="container">
  <table class="table table-borderless">
    <thead>
      <tr>
        <th>Name</th>
      </tr>
    </thead>
    <tbody>
      <% @categories.each do |category| %>
        <tr>
          <td><%= category.name %></td>
          <td class="d-flex">
            <%= link_to 'New', new_category_path, class: 'btn btn-secondary me-2' %>
            <%= link_to 'View', category_path(@category), class: 'btn btn-secondary me-2' %>
            <%= link_to 'Edit', edit_category_path(@category), class: 'btn btn-secondary me-2' %>
            <%= link_to 'Delete', category_path(@category), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-secondary me-2' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/categories/new.html.erb
<h1 class="d-flex justify-content-center p-4">Create Category</h1>
<%= render partial: 'form', locals: { category: @category, form_url: categories_path, form_method: :post, submit_button_label: "Create Category" } %>

app/views/categories/show.html.erb
<h1> Category Listed </h1>
Name: <%= @category.name %>