config/routes.rb
Rails.application.routes.draw do
  constraints subdomain: /.+/ do 
    devise_for :users, controllers: {
      registrations: 'users/registrations',
      passwords: 'users/passwords',
      sessions: 'users/sessions',
      confirmations: 'users/confirmations'
    }
    resources :members
    resources :categories
    devise_scope :user do
      get '/users/sign_out' => 'devise/sessions#destroy'
      get 'login_across_session', to: 'users/sessions#login_across_session'
    end
    get 'dashboard', to: "companies#dashboard"
    resources :installment_plans
    root to: "companies#dashboard",as: 'root_dashboard', :via => :get
  end
  constraints(subdomain: '') do
    root to: "home#index", via: :get
    devise_for :users, only: :registrations, controllers: {
      registrations: 'users/registrations'
    }
    resources :user_companies, only: :index do
      get 'find', on: :collection
    end
  end

  match "*path", to: "catch_all#index", via: :all
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  authorize_resource :company, instance_name: :current_company
  load_and_authorize_resource class: User

  #GET /members/new
  def new
    respond_to do |format|
      format.html
    end
  end

  #POST /members
  def create
    begin
      @member.company = Company.current_tenant
      @member.created_by_id = @current_user.id
      @member.new_company_member = true
      success = @member.save! 
    rescue StandardError => e
      flash[:alert] = e.message
      success = false
    end

    respond_to do |format|
      if success
        format.html { redirect_to member_path(@member), notice: 'Member was successfuly created.' }
      else
        format.html { render :new }
      end
    end
  end

  #GET /members/id
  def show
    respond_to do |format|
      format.html
    end
  end

  #GET /members
  def index
    respond_to do |format|
      format.html
    end
  end

  #GET /members/id/edit
  def edit
    respond_to do |format|
      format.html
    end
  end

  #PATCH /members/id
  def update
    begin
      success = @member.update!(member_params)   
    rescue StandardError => e
      flash[:alert] = e.message
      success = false
    end
    respond_to do |format|
      if success
        format.html {  redirect_to member_path(@member), notice: 'Member was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  #DELETE /members/id
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully deleted.' }
    end
  end

  private

  def member_params
    params.require(:user).permit(:email, :full_name)
  end

end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.erb
<div class="container">
  <%= form_for local_assigns[:member], url: local_assigns[:form_url], html: { method: local_assigns[:form_method] } do |f| %>
    <div class="pb-3">      
      <%= f.label :email %>
      <%= f.text_field :email, class: 'form-control' %>

      <%= f.label :full_name %>
      <%= f.text_field :full_name, class: 'form-control' %>
    </div>     
    <%= f.submit local_assigns[:submit_button_label], class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/members/edit.html.erb
<h1 class="d-flex justify-content-center p-4">Edit Member</h1>
<%= render partial: 'form', locals: { member: @member, form_url: member_path(@member), form_method: :patch, submit_button_label: "Update Member" } %>

app/views/members/index.html.erb
<h1 class="d-flex justify-content-center p-4">Registered Members</h1>
<div class="container">
  <table class="table table-borderless">
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @members.each do |member| %>
        <tr>
          <td><%= member.full_name %></td>
          <td><%= member.email %></td>
          <td class="d-flex">
            <%= link_to 'new', new_member_path(member), class: 'btn btn-secondary me-2' %>
            <%= link_to 'View', member_path(member), class: 'btn btn-secondary me-2' %>
            <%= link_to 'Edit', edit_member_path(member), class: 'btn btn-secondary me-2' %>
            <%= button_to 'Delete', member_path(member), class: 'btn btn-secondary', method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/members/new.html.erb
<h1 class="d-flex justify-content-center p-4">Create Members</h1>
<%= render partial: 'form', locals: { member: @member, form_url: members_path, form_method: :post, submit_button_label: "Create Member" } %>

app/views/members/show.html.erb
<h1> New Listed Members </h1>
Email: <%= @member.email %>
Name: <%= @member.full_name %>